name: ProjectEVOLVE
version: 0.5.2
main: jp.evolvegame.core.ProjectEvolvePlugin
api-version: '1.21'
author: ProjectEVOLVE
commands:
  evolve:
    description: Project EVOLVE main command
    usage: /evolve <join|leave|start|status|evolve|monster|levelup|wildlife|setmonster|setevolution|reset>
    aliases: [ev]
permissions:
  evolve.admin:
    default: op
